name: Build and push docker images (with cache)
description: Use registry to pull/push cache for an image (stages included)
author: whoan

inputs:

  username:
    description: Docker's registry user
    required: true
  password:
    description: Docker's registry password
    required: true
  registry:
    description: "(Optional) Docker registry (default: Docker Hub's registry)"
    required: false

  image_name:
    description: Name of the image to build
    required: true
  image_tag:
    description: "(Optional) Tag of the image to build (default: latest)"
    required: false
    default: latest
  context:
    description: "(Optional) Docker context (default: ./)"
    required: false
    default: .
  dockerfile:
    description: "(Optional) Name of the Dockerfile (default: Dockerfile)"
    required: false
    default: Dockerfile
  push_image_and_stages:
    description: "(Optional) Set to false to avoid pushing to registry (default: true)"
    required: false
    default: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PULL_STAGES_LOG: pull-stages-output.log
    BUILD_LOG: build-output.log

branding:
  icon: 'anchor'
  color: 'blue'
