name: Build docker images using cache
description: Use registry to pull/push cache for an image (stages included)
author: whoan

inputs:

  image_name:
    description: Name of the image to build
    required: false
  compose_file:
    description: Path to compose file
    required: false
  services_regex:
    description: (Optional) Regex to filter services from compose file
    required: false
    default: '.+'
  username:
    description: (Optional) Docker's registry user (needed to push image to repository, or to pull from private repository)
    required: false
  password:
    description: (Optional) Docker's registry password (needed to push image to repository, or to pull from private repository)
    required: false
  session:
    description: (Optional) Docker registry's session (extra auth parameters). For the AWS ECR, means setting AWS_SESSION_TOKEN environment variable).
    required: false
  registry:
    description: "(Optional) Docker registry (default: Docker Hub's registry)"
    required: false
  image_tag:
    description: "(Optional) Tag/s of the image to build (default: latest)"
    required: false
    default: latest
  context:
    description: "(Optional) Docker context (default: ./)"
    required: false
    default: .
  dockerfile:
    description: "(Optional) Name of the Dockerfile (default: Dockerfile)"
    required: false
    default: Dockerfile
  push_image_and_stages:
    description: "(Optional) Test any command before pushing. Use false to avoid pushing to registry (default: true)"
    required: false
    default: true
  stages_image_name:
    description: "(Optional) Use a custom name for the stages. Useful if using a job matrix (default: ${image_name}-stages)"
    required: false
  stages_image_tag:
    description: "(Optional) Use a custom tag for the stages image. (default: latest)"
    required: false
  push_git_tag:
    description: "(Optional) In addition to `image_tag` value, you can also push current git tag (default: false)"
    required: false
    default: false
  pull_image_and_stages:
    description: "(Optional) Set to false to avoid pulling from registry (default: true)"
    required: false
    default: true
  build_extra_args:
    description: "(Optional) Extra arguments to pass to docker build"
    required: false

outputs:
  FULL_IMAGE_NAME:
    description: Full name of the Docker Image with the Registry (if provided) and Namespace included

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'anchor'
  color: 'blue'
